# Generated by Django 2.2 on 2021-02-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulucia_web', '0012_bibliotheque1_book_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='carousel')),
            ],
        ),
        migrations.CreateModel(
            name='message_carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
