# Generated by Django 2.2 on 2021-02-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulucia_web', '0013_carousel_image_message_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='affiche1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='carousel')),
            ],
        ),
        migrations.DeleteModel(
            name='message_carousel',
        ),
    ]
