# Generated by Django 2.2 on 2020-12-31 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=45)),
                ('pays_residence', models.CharField(choices=[('Haiti', 'Haiti'), ('France', 'France'), ('Canada', 'Canada'), ('USA', 'USA'), ('R Domninicaine', 'R Dominicaine'), ('Chilie', 'Chilie'), ('Guyanne', 'Guyanne'), ('Martinique', 'Martinique'), ('Guadeloupe', 'Guadeloupe'), ('Espagne', 'Espagne'), ('Angleterre', 'Angleterre'), ('Autre', 'Autre')], max_length=45, verbose_name='Pays de residence')),
                ('telephone', models.CharField(blank=True, max_length=45, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
