# Generated by Django 2.2 on 2021-01-24 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pulucia_web.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pulucia_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_pulucia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(max_length=300)),
                ('redacteur', models.CharField(max_length=45)),
                ('categorie', models.CharField(max_length=45)),
                ('text', models.TextField(max_length=30000)),
                ('image', models.ImageField(upload_to='blog')),
                ('image_source', models.CharField(max_length=300)),
                ('views', models.PositiveIntegerField(default=0)),
                ('share', models.PositiveIntegerField(default=0)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='evenement_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('image_cover', models.ImageField(upload_to='evenement')),
            ],
        ),
        migrations.CreateModel(
            name='librairie_categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='livre_librairie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('code_livre', models.CharField(max_length=45, unique=True)),
                ('titre_du_livre', models.CharField(max_length=45)),
                ('auteur', models.CharField(max_length=45)),
                ('a_propos_du_livre', models.TextField(max_length=8000)),
                ('a_propos_de_auteur', models.TextField(max_length=8000)),
                ('annee', models.IntegerField()),
                ('page', models.IntegerField()),
                ('cover_image', models.ImageField(upload_to='librairie')),
                ('categorie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pulucia_web.librairie_categorie')),
            ],
        ),
        migrations.CreateModel(
            name='publication_auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='publication_theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='video_youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(max_length=90)),
                ('link', models.CharField(max_length=90)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.SlugField(choices=[('Poesies', 'Poesies'), ('Contes-et-Legendes', 'Contes-et-Legendes'), ('Nouvelles', 'Nouvelles')], default='poesie', max_length=45)),
                ('titre', models.CharField(max_length=300)),
                ('poeme', models.TextField(blank=True, max_length=4000)),
                ('text', models.TextField(blank=True, max_length=20000)),
                ('couleur', models.CharField(default=pulucia_web.models.publication.color, max_length=45)),
                ('views1', models.PositiveIntegerField(default=0)),
                ('share1', models.PositiveIntegerField(default=0)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulucia_web.publication_auteur')),
                ('likes1', models.ManyToManyField(blank=True, related_name='likes1', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulucia_web.publication_theme')),
            ],
        ),
        migrations.CreateModel(
            name='point_vente_livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=45)),
                ('commune', models.CharField(max_length=45)),
                ('adresse', models.CharField(max_length=45)),
                ('telephone', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('code_livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livre', to='pulucia_web.livre_librairie')),
            ],
        ),
        migrations.CreateModel(
            name='evenement_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='evenement')),
                ('note_photo', models.CharField(blank=True, max_length=100)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulucia_web.evenement_main')),
            ],
        ),
        migrations.CreateModel(
            name='comment_text2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=3000)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulucia_web.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=3000, verbose_name='Poster  un commentaire')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulucia_web.blog_pulucia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
