# Generated by Django 2.2 on 2021-01-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulucia_web', '0002_blog_pulucia_comment_article_comment_text2_evenement_main_evenement_photo_librairie_categorie_livre_'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre_librairie',
            name='categorie',
        ),
    ]
