# Generated by Django 2.2 on 2021-01-24 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulucia_web', '0004_livre_librairie_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre_librairie',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulucia_web.librairie_categorie'),
        ),
    ]
