# Generated by Django 2.2 on 2021-01-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulucia_web', '0005_auto_20210124_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librairie_categorie',
            name='categorie',
            field=models.SlugField(max_length=45, unique=True),
        ),
    ]
