# Generated by Django 2.2 on 2021-01-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulucia_web', '0006_auto_20210125_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(max_length=90)),
                ('description', models.TextField(max_length=3000)),
                ('objectif', models.TextField(max_length=500)),
                ('cible', models.TextField(max_length=400)),
                ('resultats', models.TextField(max_length=1000)),
                ('phase', models.TextField(max_length=1000)),
                ('budget', models.TextField(max_length=1000)),
                ('partenaire', models.TextField(max_length=400)),
                ('cover_img', models.ImageField(upload_to='projet')),
            ],
        ),
    ]
