# Generated by Django 2.2 on 2021-01-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulucia_web', '0008_bibliotheque1_bibliotheque_domaine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bibliotheque_domaine',
            old_name='caetegorie',
            new_name='categorie',
        ),
        migrations.AlterField(
            model_name='bibliotheque1',
            name='auteur',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='bibliotheque1',
            name='titre',
            field=models.CharField(max_length=400),
        ),
    ]
