# Generated by Django 2.2 on 2021-01-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulucia_web', '0009_auto_20210126_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliotheque1',
            name='image_cover',
            field=models.ImageField(default='', upload_to='bibliotheque'),
        ),
    ]
