# Generated by Django 2.2 on 2021-01-30 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pulucia_web', '0011_auto_20210127_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliotheque1',
            name='book_add',
            field=models.ManyToManyField(blank=True, related_name='book_add1', to=settings.AUTH_USER_MODEL),
        ),
    ]
