# Generated by Django 2.2 on 2021-02-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulucia_web', '0014_auto_20210202_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiche1',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
