# Generated by Django 2.2 on 2021-02-13 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulucia_web', '0015_auto_20210204_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='don',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('montant', models.CharField(max_length=100)),
                ('projet', models.CharField(blank=False, max_length=400)),
            ],
        ),
    ]
