# Generated by Django 2.2 on 2021-02-13 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulucia_web', '0016_don'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don',
            name='projet',
            field=models.CharField(max_length=400,   blank=False),
        ),
    ]
