# Generated by Django 2.2 on 2021-02-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulucia_web', '0017_auto_20210213_0254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='don',
        ),
    ]
