# Generated by Django 2.2 on 2021-02-13 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pulucia_web', '0019_don'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre_librairie',
            name='book_add',
            field=models.ManyToManyField(blank=True, related_name='book_add2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livre_librairie',
            name='document',
            field=models.FileField(blank=True, upload_to='librairie'),
        ),
    ]
