# Generated by Django 2.2 on 2021-02-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulucia_web', '0021_livre_librairie_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='livre_achat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=400)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('titre', models.CharField(max_length=400)),
                ('montant', models.CharField(max_length=100)),
            ],
        ),
    ]
